#pragma checksum "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "35f8a898bfe639b68e8682e99539430fa24f80fe"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\_ViewImports.cshtml"
using ChannelEngine.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\_ViewImports.cshtml"
using ChannelEngine.Web.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\_ViewImports.cshtml"
using ChannelEngine.Core.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\_ViewImports.cshtml"
using ChannelEngine.Core.Models.Order;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\_ViewImports.cshtml"
using ChannelEngine.Core.Models.Product;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"35f8a898bfe639b68e8682e99539430fa24f80fe", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"be798be75caf54eb7e050905a30c091881e9e635", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\cigdem.koc\Desktop\121010\ChannelEngine\ChannelEngine.Web\Views\Home\Index.cshtml"
  
    ViewData["Title"] = "Home Page";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<div class=""text-center"">
    <h1 class=""display-4"">Welcome</h1>
    <p> CHANNEL ENGINE CODE ASSIGNMENT</p>
    <p>This project is made according to the assignment requirements. </p>
    <p>RestSharp is used to create rest api client </p>
    <p>Please use 'Orders' menu to see the orders and top 5 sold products</p>
</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
